# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/robert/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
#resolver: nightly-2018-04-13
resolver: lts-11.5

packages:
- .
- ../rfc

extra-deps: 
- miso-0.18.0.0
- simple-logger-0.0.4
- time-units-1.0.0
- test-invariant-0.4.5.0





flags:
    base:
        integer-gmp: true
    http-api-data:
        use-text-show: true
    aeson:
        cffi: true
        fast: false
    cryptonite:
        support_pclmuldq: true
    zlib:
        non-blocking-ffi: true
    tls:
        compat: false
    bittorrent2:
        production: false
    wai-cli:
        tls: false
    postgresql-typed:
        hdbc: false
