#!/bin/bash -exu

cd `dirname $0`/..

stack build --fast 
stack test --fast --coverage
timeout --preserve-status 10s stack exec -- bittorrent2-server
timeout --preserve-status 10s stack exec -- bittorrent2-client
stack clean
stack build --haddock --haddock-deps --fast
